# Generated by Django 4.0.4 on 2022-06-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_price',
            new_name='price',
        ),
    ]
