# Generated by Django 4.0.4 on 2022-06-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_p_brand_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='p_brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='p_color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='p_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='p_price',
        ),
    ]
