# Generated by Django 4.0.4 on 2022-06-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_product_name_product_p_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_name',
            field=models.CharField(max_length=10000),
        ),
        migrations.DeleteModel(
            name='doctor',
        ),
    ]
