# Generated by Django 4.0.4 on 2022-06-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_product_p_name_delete_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=10000)),
                ('hospital_name', models.CharField(max_length=10000, null=True)),
                ('hospital_location', models.CharField(max_length=10000, null=True)),
                ('specialization', models.CharField(max_length=10000)),
                ('experience', models.CharField(max_length=10000)),
                ('gender', models.CharField(max_length=10000)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ManyToManyField(to='home.people')),
            ],
        ),
    ]
